### ISSUE TITLE
Frontend does not load up

### ISSUE THREAD

**Issue by spaceone** [stetso/mini_admin#1]
Hello,
when trying to access the web frontend I get two HTTP 404 errors:
```
GET http://localhost:5000/frontend/public/bundle.css net::ERR_ABORTED 404 (NOT FOUND)
admin:12
GET http://localhost:5000/frontend/public/bundle.js net::ERR_ABORTED 404 (NOT FOUND)
```

It seems the git repository doesn't contain the `bundle.{js,css}`.
How would I generate them? Or could you commit some static ones?

Best regards,
Florian

P.S. When starting with python3.5 I get the following traceback:
```
Traceback (most recent call last):                                      
  File "/usr/lib/python3.5/pdb.py", line 1665, in main                      
    pdb._runscript(mainpyfile)                       
  File "/usr/lib/python3.5/pdb.py", line 1546, in _runscript                   
    self.run(statement)                      
  File "/usr/lib/python3.5/bdb.py", line 431, in run                           
    exec(cmd, globals, locals)                     
  File "<string>", line 1, in <module>                   
  File "/home/fbest/.local/bin/mini_admin", line 3, in <module>
    __requires__ = 'mini-admin'                                         
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()                            
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()                    
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/fbest/Downloads/mini_admin/backend/app.py", line 7, in <module>
    from backend.models import db, User, initialize_db                               
  File "/home/fbest/Downloads/mini_admin/backend/models.py", line 2, in <module>
    from backend.config import config, db_path
  File "/home/fbest/Downloads/mini_admin/backend/config.py", line 4, in <module>
    db_path = path.join(Path.home(), '.mini_admin/')
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)                  
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'
```

I fixed this by applying this patch:
```
diff --git a/backend/config.py b/backend/config.py
index fc2c702..0fc1cbe 100644
--- a/backend/config.py
+++ b/backend/config.py
@@ -1,7 +1,7 @@
 from pathlib import Path
 from os import path

-db_path = path.join(Path.home(), '.mini_admin/')
+db_path = path.join(str(Path.home()), '.mini_admin/')

 config = dict(
   DEBUG = False,
```

**Comment by spaceone** [comment]
Ah sorry, I missed the `npm run frontend:dev` task.
